### ISSUE TITLE
Items dragged into journal won't open.

### ISSUE THREAD

**Issue by miromonti** [ironmonk88/monks-enhanced-journal#118]
Foundry: 0.8.9
MEJ: 1.0.30

I saw issues 99 and 52 and I can't figure whether this issue is the same or related, so apologies if I'm repeating....

After I dragged items into journal entries, the buttons displayed as expected, but they don't do anything. The console said this:
![image](https://user-images.githubusercontent.com/38819125/137619337-3aac9c45-b74c-4ff6-a730-645aea7e391a.png)

To be sure, I turned off MEJ and the inserted items operated correctly.

**Comment by Ouidge** [comment]
I had the same issue : Scene and Item links work fine. Actor links do not open.

I could hotfix locally by removing the "Actor" condition (`document.documentName == 'Actor' ||`) "Action 2..." case.

**monks-enhanced-journal.js, line 293:**

`            if (document.documentName == 'JournalEntry') {
`

instead of:

`           if (document.documentName == 'Actor' || document.documentName == 'JournalEntry') {
`

**Comment by miromonti** [comment]
Foundry: 0.8.9
MEJ: 1.0.33

FOLLOW-UP: This issue seems to be resolved. Actor buttons now respond by revealing the respective sheet in the journal pane. (Also, my bad for using "items" in my initial post. I meant that as generic, not an Item document. Sorry for the confusion.)

Curious observation: 

- Clicking on an Actor button in the journal reveals the sheet in the journal pane. 
- Clicking on an Item button in the journal reveals that item as a separate window.

Maybe that's the compromise that allows Actor sheets to appear? Inconsistent UX, but not a big deal, of course.

**Comment by ironmonk88** [comment]
Closing as I believe this has been fixed.
