### ISSUE TITLE
Can't unmark quests has seen or complete

### ISSUE THREAD

**Issue by Turqueso** [ironmonk88/monks-enhanced-journal#12]
When a new quest is created the "seen" and "complete" options are checked by default and when unchecked it is not saved. Also, I'm not sure whats "seen" means.

**Comment by ironmonk88** [comment]
Fixed.  I improperly used a foundry function for setting the state of a checkbox.
Thank you for catching that.
Seen was meant to be like, the players are aware of this quest.  For times when you have multiple side quests but not all of them have been revealed to the players yet.  I'm more than open to a name change on that if there's something that makes more sense.
I'm also considering adding an "Active" checkbox for quests that are actively being pursued.  But that opens up the thought that "Not Revealed", "Seen", "Active", and "Completed" can go into a drop down list as state, rather than using multiple check boxes.

**Comment by Turqueso** [comment]
Thanks for the quick fix! It's an awesome module. Maybe "In progress" or "Active" would be more clear instead of "Seen"?
But I agree that maybe a drop down list would make more sense if there's going to be more options

**Comment by ironmonk88** [comment]
I've updated this to combine the two into a status drop down.
