### ISSUE TITLE
[Request] Implement natural sorting for journal entries

### ISSUE THREAD

**Issue by dmrickey** [ironmonk88/monks-enhanced-journal#128]
![image](https://user-images.githubusercontent.com/3664822/142552070-a8ba2e36-1bc0-40e4-9b2d-a55c025c5deb.png)
It would be nice if these could be ordered 1,2,3...9,10,11.

**Comment by ironmonk88** [comment]
If you edit the folder you can change it to manual sorting and change the order yourself.
![image](https://user-images.githubusercontent.com/75920956/143729494-bf8a1587-3173-48e0-9f85-a8a376f08a81.png)
I like the idea of detecting numbers to sort that way... but it's a huge change, and would need to overwrite a lot of Foundry code.  Which I'm not sure is that time effective, since there is any easy alternative by setting it to manual and moving the items around yourself.

**Comment by FadedMaster** [comment]
Another option is using a leading zero. This is how filenames used to have to be before operating systems would detect numbers that way.

**Comment by ironmonk88** [comment]
Closing this as there is a workaround.
And I think it's a bit beyond the scope of MEJ.
