### ISSUE TITLE
Making GM able to see player notes on "Person" journals

### ISSUE THREAD

**Issue by Horozarai** [ironmonk88/monks-enhanced-journal#140]
Hi. 

I've noticed that my GM isn't able to see the notes i put in on Person journals. 
I really think this is too bad, since it would give him a lot of insight into my thoughts and observations of different NPC's in his game. 

I know not all GM's would want to see their players notes. So a possible fix for this could be to make a togglable checkbox in the module settings that would allow the GM to see player notes? 
I don't know how hard this would be, since I'm terrible at coding myself?
 
If possible, maybe the notes could even be divided into sections, so each player has its own section, when in GM view?
I know i might be pressing my luck, but we just have so much enjoyment from the module, and i really helps organize our game.

Thanks a bunch for your efforts!

**Comment by ironmonk88** [comment]
I think it might be a bit too complicated.
Because you wouldn't be the only player the GM might want to see.  So you'd have to provide an interface to cycle through each players potential responses.

What I'd suggest doing instead, is have your GM assign each of you your own Journal Entry.  That way you can store private notes on the Person Journals, but share notes you've collected in your Adventure Journal.  And that way the GM can see your Adventure Log.  I'd also recommend dragging a link to the Person Entry onto your Adventure Log so that you can quickly switch to the NPCs encountered and check to see if you have private notes.

Not completely what you were wanting but I think it might be more of a feasible solution.

**Comment by ironmonk88** [comment]
Closing this as it goes against what I want to do with MEJ and there's a workaround solution.
