### ISSUE TITLE
Unable to open journals from PF Content Module

### ISSUE THREAD

**Issue by Fair-Strides** [ironmonk88/monks-enhanced-journal#141]
The journal entries from FadedShadow's PF Content Module all have the type "journal", or the type 'undefined' upon first being opened in the Enhanced Journal.

Comparing to an "Enhanced Journal Entry" made using this module found that the "Enhanced Journal Entry" has a type of "base", so I had to manually change a sample entry from PF Content to type "base" to open it in the Enhanced Journal.

I _think_ this could be fixed by having the Enhanced Journal default to a type "base" instead of "undefined".

**Comment by apetina** [comment]
Pretty sure it is related to this issue (because it also happened to me in the same circumstances), I get this error when I try to open journals that hasn't been created using the module:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/78870451/146081997-2f2f80ad-4816-4754-8e88-7e7b936c923d.png">

**Comment by ironmonk88** [comment]
There's been a couple of upgrades, is this still an issue?
And if you deselect Lib: Document Sheet Registrar does that make it better?

**Comment by Fair-Strides** [comment]
I am not sure yet as I've not been upgrading to v9 yet, but I will let you know as soon as I can.

**Comment by apetina** [comment]
For me it looks it is working properly in Foundry V9 and deselecting Lib: Document Sheet Registrar

**Comment by ironmonk88** [comment]
Closing as it looks like it's working.
