### ISSUE TITLE
More than 1 quest objective breaks editing and notifications

### ISSUE THREAD

**Issue by aranian** [ironmonk88/monks-enhanced-journal#148]
Once you add a second objective to a quest, the editing of objectives breaks. You are unable to remove the 'Visible' and 'Completed' flags from any objective of that quest in the overview. When editing an objective in the dialog you can remove the check-marks, but only the 'Visible' flag is actually saved.
Furthermore the quest list in the notification tool no longer displays a dot or check-mark and completed objectives no longer have a line through them.
Before adding the second objective:
![image](https://user-images.githubusercontent.com/731750/147396009-175022e3-3a25-45f4-8416-fb3445259287.png)
After adding a second objective and marking it complete:
![image](https://user-images.githubusercontent.com/731750/147396024-0d7d841e-7dae-4b6f-9108-233bbb3c5f32.png)

**Comment by ironmonk88** [comment]
This should be added to the latest release.
Foundry changed the way it collects data from lists on a page, that I suspect is a bug.  But it was specifically changed so I'm not sure.  In v8 it would return an array of true or false depending on the value of the checkbox.  In v9 it just returns the ones that are checked.  And since it's an array, there's no way to tell which checkbox is on or off.
I added code for Quests, Encounters, and Shops to recreate collecting data to way it was in v8.
