### ISSUE TITLE
[Suggestion] Store Improvements

### ISSUE THREAD

**Issue by aranian** [ironmonk88/monks-enhanced-journal#155]
It would be nice to be able to sort a store's content. Either alphabetically and/or via drag & drop.
I'm not entirely sure what the difference between price and cost is supposed to be? Is it single item and total?
The PF2 system already has item prices available, it would be very convenient if that price was added to the store.
The 'price' field has no structure, meaning you can enter any string.

Is the shop not supposed to interact with a player's currency? I might use the PF2 'Loot (Merchant)' actor type, as it has some of these functionalities built in. But those are 1) stored as an actor instead of a journal entry and 2) not system-agnostic.

**Comment by ironmonk88** [comment]
Store content is now sorted alphabetically.

Cost is what you show the players, price is what the item is set to.  At some point there's going to be an improvement where you can adjust the cost of all the items at once.

There was an issue converting, that should be fixed and the prices should be appearing now in PF2.

And you can enter any string... because it's trying to be system agnostic.  And gold isn't exactly system agnostic.  Which is why it doesn't interact with player's currency at the moment.  I havn't found a good way to do it yet.

**Comment by ironmonk88** [comment]
Shops should be interacting with player currency now.
Closing the ticket as all the points should be covered.
