### ISSUE TITLE
Shop and Encounter entries do not save until an item has been added 1.0.39

### ISSUE THREAD

**Issue by james0x0A** [ironmonk88/monks-enhanced-journal#161]
New shop and encounter entries do not save until and item has been added to the shop or encounter reward section. Until an item is added to the entry `getFlag("monks-enhanced-journal", "items")` returns undefined and throw when trying to clone the object while saving.

Here is a snippet from the trace on a shop journal entry when saving the entry before adding any item.
```
VM4142:1 Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at duplicate (helpers.mjs:118)
    at ShopSheet._getSubmitData (ShopSheet.js:206)
    at ShopSheet._onSubmit (EnhancedJournalSheet.js:315)
    at ShopSheet.saveEditor (foundry.js:3966)
    at ShopSheet.subsheet.saveEditor (enhanced-journal.js:248)
    at _x.save_onsavecallback (foundry.js:4003)
```

**Comment by valundir** [comment]
I have seen a similar issue with Encounter entries since about last November. If I create a new world and load only Monk's Enhanced Journal module and then create a new journal entry and switch it to Encounter type then anything I type in the journal window is unsaved. If I first convert to Journal Entry type and save it will stay saved but anything written while it is in Encounter mode will not save. Furthermore, I am unable to change the # of Monsters in the Details tab. If I change the Qty it gets reset to 1 every time I close and reopen the record. Items do not seem to have this issue and DC's work fine as well. I went back to an older version of the module from last October and it does not have this issue.

**Comment by webmaster94** [comment]
The strangest thing is that I got one of my shops to stop behaving like this and I have no idea what I did to get it to work.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
