### ISSUE TITLE
Actors Linked in Handouts Not Opening

### ISSUE THREAD

**Issue by ghost** [ironmonk88/monks-enhanced-journal#173]
If an actor is linked in a handout, the link seems to TRY to open through enhanced journal rather than opening the actor in a new window just like items do. It shows a blank note.

**Comment by ironmonk88** [comment]
That because Enhanced Journals will show Actor sheets within the enhanced browser.
The issue was with it displaying blank, and I think that's been fixed.
Hold CTRL to open it in a new tab, or SHIFT to open it in a new window.
And there's also a setting that will by default open links outside of Enhanced Journal instead of within it.
