### ISSUE TITLE
Feature Request: Make shop use different currencies

### ISSUE THREAD

**Issue by igorgsouza** [ironmonk88/monks-enhanced-journal#208]
Pretty much the title, make so that we can use different currencies on shop prices. Also it would be great if it would automatically convert (like you have 1 silver, spend 3 copper and it automatically sets you to 7 copper)

AMAZING MODULE BTW

**Comment by ironmonk88** [comment]
The conversion is something I've left up to the GM because most systems don't include any information on how to convert.  So there's no way to tell Enhanced Journals how a conversion should happen.  Also there may be times when a conversion can't happen (Although I think most GMs don't really worry about how the actual conversion happens) 

As for using different currency... it can already do that.  Just change the price to `2 cp` or `10 sp`.  It's only defaulting to gold because you havn't told it explicitly what you're using so it doesn't really know.

**Comment by LonePaladin** [comment]
I found the setting where you can tell the module what currencies you use, and their exchange rate. I changed the settings for my PF2 game so that `sp` is the default, with everything else converting on a 1:10 scale as usual.

Prices in PF2 items are listed in their relevant currency (such as `2 cp` or `10 gp`, but when I drag them into a journal entry's store list, it converts the price to `sp` without changing the amount. So if I have an item that costs `10 gp`, it will display `10 sp`.

I haven't yet tried running this with a PC to see how it handles purchasing.

**Comment by ironmonk88** [comment]
Closing this as I've added automatic conversion.  And using different currency is already covered.
I'm also unable to replicate issues with setting silver as the default so I suspect that was also fixed.
