### ISSUE TITLE
Viewing a 'Picture' type journal entry makes text journal entries blank when switching back to them

### ISSUE THREAD

**Issue by amcvfx** [ironmonk88/monks-enhanced-journal#25]
I've created a number of text only and picture only journal entries but the text entries appear blank if viewed after a picture only entry.
Possibly because it's trying to switch to an image when there isn't one?

**Comment by ironmonk88** [comment]
It's saving the last tab it was on, because that's the default when you can open multiple windows with journal entries.  But that becomes a complication when you're opening each entry in one window.  So if you're viewing an old journal entry that has both a picture and description, you can switch the between the tabs.  But when you switch to a new Journal Entry, the tabs are hidden (because there's a picture Journal Entry, the two don't need to be combined).
I've updated the code so that it will reset the tabs and pick the one that makes the most sense for the Journal Entry.

...and I'm considering not hiding the tabs at all.  And letting a Journal Entry store both.  Regardless of if it's old or new.

**Comment by ironmonk88** [comment]
Showing Description and Picture for all Journal Entries.
