### ISSUE TITLE
[BUG] Loot Journals and Assigning Currency

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#349]
![image](https://user-images.githubusercontent.com/99844555/181345514-f9e79393-49d2-42bc-a3b0-3f57887d58d3.png)
Manually typing in a currency value to a character results in the value being added to the total, instead of being subtracted from the currency pool.

Foundry 9.269
D&D 5e 1.0.63
MEJ 1.0.65

**Comment by ironmonk88** [comment]
That's expected behavior.  The total, is the total of what the players have and what's in the "reserve".
It's done that way, so if the "reserve" doesn't split evenly you can add just a little bit more to top it up.

So essentially MEJ doesn't know if the GM wants to balance everything, or if they want to customize the values.  Does the total create the values, or do the values create the total.  And since I want to allow for GM flexibility I opted for the values to create the total.

This allows the GM to add a little extra to some characters, and then click the split button and have the "reserve" split evenly, with the "little bit extra" preserved when split.
