### ISSUE TITLE
[BUG] V10. Page View Not Saving

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#393]
### Core 

Whether you have "multiple page view" or "single page view" is tracked between closing the journal and reopening it.

https://user-images.githubusercontent.com/99844555/192206661-561e9c3c-44a6-4b86-8053-22d11406fe99.mp4

### MEJ

It reverts back to "single page view" when closing & reopening.

https://user-images.githubusercontent.com/99844555/192206598-2b5ab01b-64d7-417e-8000-7ba82c48fc7b.mp4

**Comment by ironmonk88** [comment]
I'm not sure there's anything I can do about this.
Foundry has quite effectively locked me out from manually setting the mode, so when the sheet gets re-rendered it resets the mode, and I can't change it back.
I tried using the function call to toggle the mode if it's different from the enhanced journals mode... but that calls the render function which isn't playing nice since it's in the middle of a render already.
So I'm not really sure what to do about this one.
I think it's a Foundry fault that I'm having troubles working around.

**Comment by ironmonk88** [comment]
I found a workaround.
Should be in the latest version.
