### ISSUE TITLE
[Feature Request] MEJ Font

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#443]
Core journal fonts adjust when the main Foundry font is adjusted; user is requesting this added to MEJ journals as well.

**Comment by Nedrapter** [comment]
Thank you for being faster than me, lol! I just came here to post this ^^ Please save me from going blind and let font size adjust with the core setting!

**Comment by davidhawbecker** [comment]
I will second this request. I've been changing the font size manually on each page and realized there has to be a better way. If anyone can figure it out it's Monk.

**Comment by Crowguard** [comment]
Font size isn't changing in MEJ 10.7.

https://user-images.githubusercontent.com/99844555/209904704-2ead6c47-657b-4b5e-8e06-6ba572eb44d8.mp4

MEJ 10.7
Foundry 10.291
FTC ✔️

**Comment by ironmonk88** [comment]
That's expected.  It is changing font size for the interface, but I can't change the font size in the actual document... because users may want the document formatted with a specific font.
I did add a new option for dynamic fonts
![image](https://user-images.githubusercontent.com/75920956/210014594-54adc091-0682-49fd-8733-09401691621e.png)
It's not the best, but it'll give people the option to use fonts based the core font size.

**Comment by Crowguard** [comment]
That makes sense, to not break existing stuff.

I did go back, swap this test one over to the dynamic font, and they still don't change. Not sure what the cause is. I'm not having issues in other journals with it now.
https://user-images.githubusercontent.com/99844555/210018608-a7a46385-0552-4d90-bc86-1b45936ac4a7.mp4

[fvtt-JournalEntry-journal.zip](https://github.com/ironmonk88/monks-enhanced-journal/files/10322427/fvtt-JournalEntry-journal.zip)
