### ISSUE TITLE
[BUG] Journal Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#488]
Occurred when opening PF2E Beginner Box's journals. Didn't seem to be affecting anything I could see. Let me know on Discord and I can DM you the journal if I need to.

![image](https://user-images.githubusercontent.com/99844555/214983295-4dd799da-785d-4e27-b5d7-6da548217cb9.png)

Foundry 10.291
PF2 4.6.8
MEJ 10.12

**Comment by ironmonk88** [comment]
That's 100% a Pathfinder bug.
I'm assuming it's the same code they use for Abomination Vaults.
Shouldn't happen for journal entries, but does happen for Actors in a Journal tab... because PF2E doesn't have any error checking to make sure the data passed is actually a Journal Sheet.
And... justifiably so, since you wouldn't expect a Journal to display anything other than a Journal Page.

**Comment by ironmonk88** [comment]
Not so much a won't fix, as a can't fix.
