### ISSUE TITLE
[BUG] When buying an upmarked item the price of the item changes permanently [Foundry v10]

### ISSUE THREAD

**Issue by NnickozZ** [ironmonk88/monks-enhanced-journal#527]
**Describe the bug**
When a shop has a markup and I buy the item, the item permanently gains the marked-up price in the value space permanently.

**To Reproduce**
Try it out on foundry v10, this worked correctly in v9.
1. Create a Monks Shop
2. Give all items a markup or change the 'cost' of an item in the shop
3. Purchase item
4. Check the purchased item price

**Expected behavior**
The value of the item should stay the original value even though the 'cost' has been changed

**Screenshots**
![image](https://user-images.githubusercontent.com/98185606/222979116-330c11cb-cc46-4b81-95f3-e25ecbb9d2f3.png)
![image](https://user-images.githubusercontent.com/98185606/222979122-9ec6de3a-d669-447c-bfcc-82025001cca1.png)

**Please complete as much of the following information as possible:**
 - Foundry Version [V10]
 - System [D&D 5e]
 - Module version: 10.14

**Comment by kay1010100** [comment]
I can confirm this issue is still pressent.

- Browser [chrome]
- Foundry Version [V11 Stable 315]
- System [DnD5e v2.4.1]
- Module version: 11.07

**Comment by ironmonk88** [comment]
That is done by design.  A pot bought at 3gp is worth 3gp.  Let's say that you have a shop that marks an item up 10x what it's commonly worth.  So that pot sells for 10gp.  If the player went to sell that item back to the shop, instead of the shop buying back for half of what it's worth (5gp) the price of the pot would drop to 2gp and be bought back for 1gp.  And that's not according to the game rules.

I've added a setting if you really want to break game rules, but I'd advise against it as your players could exploit it pretty easily.

**Comment by ironmonk88** [comment]
Also, bear in mind, v10 is no longer supported, so changes are v11 only.

**Comment by ironmonk88** [comment]
Added the setting in the latest version.
