### ISSUE TITLE
[BUG] Loot Journal Transfer Currency

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#598]
Currently unable to add actors to the transfer window. No errors.

https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/5ee4dceb-ecc1-4db6-beaa-7bb09ec85842

MEJ 11.02
Foundry 11.305

**Comment by ironmonk88** [comment]
Sooooo... that's technically working as intended.  The GM isn't supposed to use that dialog.  Only the players. GM is supposed to use the distribute dialog.
So it's erroring out... because you don't have a character attached to you.
But I see how that could be useful for the GM to be able to use it the way you're indicating.

**Comment by ironmonk88** [comment]
Should be added to the latest release.
